### ISSUE TITLE
[CMS] Progressive image sizes on 'Text - two columns' CCT

### ISSUE THREAD

**Issue by jporich** [unimelb/design-system-issues#57]
At present the images used in 'Text - two columns' CCT will only make use of the originally sized image and not first check for image variants

## User story
As an editor, I want to select images for use in my CCTs and not have to worry about always selecting the right image variety so that my pages always load fast and I can focus on other content, rather than image editing. 

## Requirements

**(See page listing CCT for Squiz keyword implementation)**

CCT should check for presence of image variants in the following order:

1. "large" image variant of selected image
2. "medium" image variant of selected asset
3. Fall back to the original size if neither large nor medium variants are present 

Notes:
- Banner is too large to use - thumb is too small.
- If no medium or large variant available, this indicates that the selected image was not large enough to have had these variants auto-create upon upload (therefore, original size is the final fallback)
- At present CSS is targeting a maximum viewport width of >769px - so these maximum sizes should suit all viewports
- The maximum possible image size presented will have a width of 43.75rem (582.750px) 

CSS which sets image size at present is: 

```css
@media screen and (min-width: 769px)
.uomcontent .half>section, .uomcontent [role=main] .half>section {
    padding: 1.875rem .9375rem;
    display: table-cell;
    vertical-align: top;
    width: 50%;
}
```

Parent container of the `.half`'s `section` is:
```css
@media screen and (min-width: 769px)
.uomcontent .half, .uomcontent [role=main] .half {
    max-width: 87.5rem;
    display: table;
}
```

## Usage
All pages making use of the CCT 'Text - two columns'

Example page with multiple Text - two columns CCTs making use of large original images
https://cms.unimelb.edu.au/controlled-environment/law/students/opportunities-scholarships-careers/opportunities/study-law-exchange/_nocache#and-12-a-half

### Assumptions include: 
- Can be implemented to existing CCTs
- Will account for images with no Image Variants
- Meets [UoM Brand Guidelines](https://brandhub.unimelb.edu.au)
- Meets  [WCAG 2.0 Level AA](https://www.unimelb.edu.au/accessibility/home) requirements
- [Markup is valid via W3C](https://validator.w3.org/)
- Meets SEO requirements
